server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pedidos360
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/f808e7f8-d340-4129-aa19-44b19281283a/