services:
  backend:
    build:
      context: ./ms-pedidos360-bff
    ports:
      - "8083:8083"
    environment:
      DB_URL: jdbc:mysql://host.docker.internal:3306/pedidos360
      DB_USERNAME: root
      DB_PASSWORD: 1234

  frontend:
    build:
      context: ./frontend-pedidos360
      args:
        VITE_API_URL: http://localhost:8083
    ports:
      - "80:80"
