services:
  mysql:
    image: mysql:8.0
    environment:
      # TODO: cambiar este valor antes de usar en produccion
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pedidos360
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      # Opcional: solo si necesitas conectarte desde fuera del compose para debug
      - "3307:3306"

  backend:
    build:
      context: ./ms-pedidos360-bff
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/pedidos360
      DB_USERNAME: root
      DB_PASSWORD: 1234

  orders:
    build:
      context: ./ms-pedidos360-orders
    ports:
      - "8087:8087"
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/pedidos360
      DB_USERNAME: root
      DB_PASSWORD: 1234

  catalog:
    build:
      context: ./ms-pedidos360-catalog
    ports:
      - "8086:8086"
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/pedidos360
      DB_USERNAME: root
      DB_PASSWORD: 1234

  frontend:
    build:
      context: ./frontend-pedidos360
      args:
        VITE_API_URL: http://100.28.101.134:8083
    ports:
      - "80:80"

volumes:
  mysql_data:
