spring:
  application:
    name: ms-pedidos360-notify
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
app:
  rabbitmq:
    notifications-queue: ${NOTIFICATIONS_QUEUE:order.notifications}
management:
  endpoints.web.exposure.include: health,info
