server:
  port: ${SERVER_PORT:8086}
spring:
  application:
    name: ms-pedidos360-catalog
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/pedidos360}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_AD_ISSUER_URI:https://login.microsoftonline.com/f808e7f8-d340-4129-aa19-44b19281283a/v2.0}
